# Generated by Django 5.1.4 on 2025-01-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0003_alter_todo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=6,
            ),
        ),
    ]
